export const TYPES = {
  
  //Auth
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  RESET_ERROR: "RESET_ERROR",

  //Data
  SET_GIFS: "SET_GIFS",
  SET_USER_GIFS: "SET_USER_GIFS",
  SET_OTHER_GIFS: "SET_OTHER_GIFS",
}